### ISSUE TITLE
[Windows] ImportError: DLL load failed while importing moving_statistics (Microsoft Visual C++ 2015 Redistributable dependency) 

### ISSUE THREAD

**Issue by MichellevM** [pfizer-opensource/scikit-digital-health#105]
Using dependencies.exe I found out that the package has some broken dependencies on newly installed machine.

<img width="960" alt="DependenciesTool_" src="https://github.com/PfizerRD/scikit-digital-health/assets/34157548/e854df44-5bcf-4d5f-9186-14d1ace67f02">

It seems that these dependencies are part of the Microsoft Visual C++ 2015 Redistributable Update 3.
https://windll.com/dll/other/libgcc-s-seh-1
https://windll.com/dll/other/libquadmath-0
https://windll.com/dll/mingww64-project-all-rights-reserved/libwinpthread-1

The download page for Microsoft Visual C++ 2015 Redistributable Update 3:
https://www.microsoft.com/en-us/download/details.aspx?id=53587

Can this windows dependency be added to the installation guide and https://pypi.org/project/scikit-digital-health/  ?

**Comment by masoudabedinifar** [comment]
Hey, I was trying to install the package on my local PC and then wanted to run the example notebook. However, I ran into the same issue

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[c:\Users\Project\Desktop\scikit-digital-health\examples\skdh_examples.ipynb](file:///C:/Users/Project/Desktop/scikit-digital-health/examples/skdh_examples.ipynb) Cell 1 line 5
      [2](vscode-notebook-cell:/c%3A/Users/Project/Desktop/scikit-digital-health/examples/skdh_examples.ipynb#W0sZmlsZQ%3D%3D?line=1) import pandas as pd
      [3](vscode-notebook-cell:/c%3A/Users/Project/Desktop/scikit-digital-health/examples/skdh_examples.ipynb#W0sZmlsZQ%3D%3D?line=2) from plotly import graph_objects as go
----> [5](vscode-notebook-cell:/c%3A/Users/Project/Desktop/scikit-digital-health/examples/skdh_examples.ipynb#W0sZmlsZQ%3D%3D?line=4) from skdh.io import ReadCwa

File [c:\Users\Project\anaconda3\envs\pfizer\lib\site-packages\skdh\__init__.py:31](file:///C:/Users/Project/anaconda3/envs/pfizer/lib/site-packages/skdh/__init__.py:31)
     28 from skdh.pipeline import Pipeline
     29 from skdh.base import BaseProcess
---> 31 from skdh import utility
     32 from skdh import io
     33 from skdh import preprocessing

File [c:\Users\Project\anaconda3\envs\pfizer\lib\site-packages\skdh\utility\__init__.py:52](file:///C:/Users/Project/anaconda3/envs/pfizer/lib/site-packages/skdh/utility/__init__.py:52)
     50 from skdh.utility.fragmentation_endpoints import *
     51 from skdh.utility import fragmentation_endpoints
---> 52 from skdh.utility.math import *
     53 from skdh.utility import math
     54 from skdh.utility.orientation import correct_accelerometer_orientation

File [c:\Users\Project\anaconda3\envs\pfizer\lib\site-packages\skdh\utility\math.py:11](file:///C:/Users/Project/anaconda3/envs/pfizer/lib/site-packages/skdh/utility/math.py:11)
      7 from warnings import warn
      9 from numpy import moveaxis, ascontiguousarray, full, nan, isnan
---> 11 from skdh.utility import _extensions
...
   (...)
     18     "moving_min",
     19 ]

ImportError: DLL load failed while importing moving_statistics: The specified module could not be found.
```

I have updated the Microsoft Visual C++ 2015 Redistributable, but was still not able to run the example. Is there any update on a fix for this?

**Comment by masoudabedinifar** [comment]
I tried to install the package using all of the alternatives one by one including pip, conda, and also building from the source.

**Comment by LukasAdamowicz** [comment]
Pip should be the most reliable, as there should be a windows wheel, but I've been struggling to get a reliable working solution for windows installs, especially since I dont have a good way to test on windows, sorry.
