### ISSUE TITLE
Is inertial data from Xsens Dot supported?

### ISSUE THREAD

**Issue by nie911** [pfizer-opensource/scikit-digital-health#145]
Dear developers, does SKDH support inertial data from Xsens Dot？The data file includes timestamp, three-axis acceleration and three-axis angular velocity.
[103142-20230423-W03.csv](https://github.com/pfizer-opensource/scikit-digital-health/files/14791033/103142-20230423-W03.csv)

**Comment by nie911** [comment]
The above document is incorrect, you can use this document as a reference.
[111745-20230423-W03.csv](https://github.com/pfizer-opensource/scikit-digital-health/files/14791121/111745-20230423-W03.csv)

**Comment by LukasAdamowicz** [comment]
Hi,
Yes, you should be able to import the data using this command:

```python
import skdh

rdr = skdh.io.ReadCSV(
    time_col_name="SampleTimeFine",
    column_names={
        'accel': ['Acc_X', 'Acc_Y', 'Acc_Z'],
        'gyro': ['Gyr_X', 'Gyr_Y', 'Gyr_Z']
    },
    read_csv_kwargs={'skiprows': 1},
    to_datetime_kwargs={'unit': 's'},  # TODO this needs to be changed,
    accel_in_g=False,
    g_value=9.81,
)
```

Please note that the timestamp units are NOT correct, but at a quick look I'm not sure what the exact conversion is, but you can specify it using the `to_datetime_kwargs` parameter, and pass in any [pd.to_datetime](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html) key-word arguments that you need to convert it appropriately
